### ISSUE TITLE
Browser source code

### ISSUE THREAD

**Issue by autc04** [ctm/executor#5]
Is the source code for the Browser application included in the executor repository still around somewhere?
Can it be made available?
Or is it lost in the depths of history?

**Comment by MaddTheSane** [comment]
I think [this](https://github.com/ctm/executor/tree/master/packages/go) is either it, or shared resources for it.

**Comment by autc04** [comment]
Duh, I somehow failed to make the connection between the app's icon and the name of that directory...
Yes, that's it.
Thanks!
